# -*- coding: utf-8 -*-
"""Qori review decisions, stored apart from the registry they apply to.

WHY AN OVERLAY AND NOT AN EDIT IN PLACE
---------------------------------------
tajweed_error_registry_v3.json is GENERATED by tools/apply_v3_patch.py and says
so in its own _meta. If the review screen wrote `status: "reviewed"` back into
it, the next regeneration would silently discard every approval a qori had
given - the most expensive data in the project, produced by the scarcest person
in it.

So decisions live in their own file and are merged at load time by
coverage.registry(). Regeneration cannot touch them, the audit trail diffs
cleanly on its own, and a reviewer's edits to the Uzbek survive a rebuild of the
catalogue underneath them.

WHAT A DECISION CONTAINS
------------------------
    status      reviewed | rejected | draft   (draft = decision withdrawn)
    uz          ONLY the fields the reviewer actually changed, so an edit does
                not freeze a copy of the rest and stop tracking the source
    reviewed_by who said so - required for approve and reject
    reviewed_at when

Nothing here authors content. The uz overrides are whatever a qualified reviewer
typed; this module only stores and replays them.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

PATH = Path(__file__).resolve().parents[3] / "tajweed_registry_review.json"

VALID = {"reviewed", "rejected", "draft"}
# The learner-facing fields of a registry uz block. An edit may touch these and
# nothing else - a reviewer must not be able to rewrite `group` or
# `detection_confidence` through the content editor.
UZ_FIELDS = ("name", "short", "nima_xato", "qoida", "nega_muhim",
             "tuzatish", "mashq")


def _empty() -> dict:
    return {
        "_meta": {
            "purpose": "Qori review decisions for tajweed_error_registry_v3.json.",
            "why_separate": (
                "v3 is generated by tools/apply_v3_patch.py. Writing approvals "
                "into it would lose them on the next regeneration. This file is "
                "merged over the registry at load time by coverage.registry()."),
            "status_values": {
                "reviewed": "a qualified qori signed the Uzbek text off",
                "rejected": "seen and refused - stays out of the learner's way",
                "draft": "no decision, or a decision withdrawn",
            },
            "edits": (
                "`uz` holds ONLY the fields a reviewer changed. Anything absent "
                "still tracks the generated registry."),
        },
        "decisions": {},
    }


def load() -> dict:
    """Read fresh every time. This file is written by a human through the review
    screen while the server is running, so a cache here would serve a stale
    queue back to the person who just edited it."""
    if not PATH.exists():
        return _empty()
    try:
        data = json.loads(PATH.read_text(encoding="utf-8-sig"))
    except (json.JSONDecodeError, OSError):
        # A corrupt decisions file must not take the API down, but it must not
        # be silently treated as "nothing was ever reviewed" either.
        raise RuntimeError(
            f"{PATH.name} is unreadable. It holds every qori approval - fix or "
            f"restore it rather than deleting it.")
    data.setdefault("decisions", {})
    return data


def decisions() -> dict:
    return load()["decisions"]


def apply_overlay(errors: dict) -> dict:
    """Registry entries + review decisions. Returns a new dict; never mutates."""
    got = decisions()
    if not got:
        return errors
    out = {}
    for code, entry in errors.items():
        d = got.get(code)
        if not d:
            out[code] = entry
            continue
        merged = dict(entry)
        if d.get("status") in VALID:
            merged["status"] = d["status"]
        for key in ("reviewed_by", "reviewed_at", "review_note"):
            if d.get(key):
                merged[key] = d[key]
        edits = {k: v for k, v in (d.get("uz") or {}).items() if k in UZ_FIELDS}
        if edits:
            merged["uz"] = {**(entry.get("uz") or {}), **edits}
            merged["uz_edited_fields"] = sorted(edits)
        out[code] = merged
    return out


def record(code: str, status: str, *, reviewed_by: str = "",
           uz: dict | None = None, note: str = "") -> dict:
    """Persist one decision and return it.

    Writes the whole file each time. It is a few kilobytes and edited by one
    person at a time; anything cleverer would be a concurrency bug waiting for
    a second reviewer that does not exist yet.
    """
    if status not in VALID:
        raise ValueError(f"status must be one of {sorted(VALID)}, got {status!r}")
    if status in ("reviewed", "rejected") and not reviewed_by.strip():
        # An approval with no name attached is not an audit trail, and this is
        # the record that says a human vouched for a ruling about the Quran.
        raise ValueError("reviewed_by is required to approve or reject")

    data = load()
    prev = data["decisions"].get(code, {})
    entry = {
        "status": status,
        "reviewed_by": reviewed_by.strip() or prev.get("reviewed_by", ""),
        "reviewed_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    if note.strip():
        entry["review_note"] = note.strip()

    # Edits accumulate: approving after an edit must not drop the edit.
    merged_uz = {k: v for k, v in (prev.get("uz") or {}).items()
                 if k in UZ_FIELDS}
    for key, value in (uz or {}).items():
        if key in UZ_FIELDS and isinstance(value, str):
            merged_uz[key] = value
    if merged_uz:
        entry["uz"] = merged_uz

    data["decisions"][code] = entry
    PATH.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n",
                    encoding="utf-8")

    # coverage.registry() is lru_cached, so the next read would serve the state
    # from before this decision without this.
    from . import coverage
    coverage.registry.cache_clear()
    coverage.in_scope.cache_clear()
    return entry
