# -*- coding: utf-8 -*-
"""Precompute practice segments for all 6236 ayat -> tilawah/content/segments.json

Build-time only, committed to the repo. Segmenting one ayah costs 0.2-3 s
(get_by_imlaey_words alone is ~60 ms/call) and that has no business in a request
path, so the whole book is packed once here.

Run:  python tools/build_segments.py
"""
import json
import sys
import time
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from quran_transcript import Aya  # noqa: E402

from tilawah.engine.ranges import (HARD_CAP_SECONDS, RATE_DISPLAY, RATE_GATE,  # noqa: E402
                                   TARGET_SECONDS)
from tilawah.engine.segmentation import exceeds_cap, segment_ayah  # noqa: E402

OUT = ROOT / "tilawah" / "content" / "segments.json"


def main() -> int:
    data: dict[str, list[list[int]]] = {}
    over_cap: list[str] = []
    per_sura: dict[int, int] = {}
    t0 = time.perf_counter()
    n_seg = 0

    for sura in range(1, 115):
        n_ayat = Aya(sura, 1).get().num_ayat_in_sura
        count = 0
        for aya in range(1, n_ayat + 1):
            segs = segment_ayah(sura, aya)
            data[f"{sura}:{aya}"] = [
                [s.start_word, s.num_words, s.n_phonemes] for s in segs]
            for s in segs:
                if exceeds_cap(s):
                    over_cap.append(f"{sura}:{aya} w[{s.start_word}:"
                                    f"{s.start_word + s.num_words}] "
                                    f"{s.seconds_gate:.1f}s")
            count += len(segs)
        per_sura[sura] = count
        n_seg += count
        print(f"sura {sura:3d}: {n_ayat:3d} ayat -> {count:4d} segments "
              f"({time.perf_counter() - t0:.0f}s)", flush=True)

    payload = {
        "_meta": {
            "note": "Generated by tools/build_segments.py. Do not hand-edit.",
            "rate_display_s_per_phoneme": RATE_DISPLAY,
            "rate_gate_s_per_phoneme": RATE_GATE,
            "target_seconds": TARGET_SECONDS,
            "hard_cap_seconds": HARD_CAP_SECONDS,
            "n_ayat": len(data),
            "n_segments": n_seg,
            "segments_over_hard_cap": over_cap,
            "format": "sura:aya -> [[start_word, num_words, n_phonemes], ...]",
        },
        "segments": data,
    }
    OUT.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
                   encoding="utf-8")

    print(f"\n{'=' * 60}")
    print(f"{len(data)} ayat -> {n_seg} segments in "
          f"{time.perf_counter() - t0:.0f}s")
    print(f"artifact: {OUT}  ({OUT.stat().st_size / 1e6:.2f} MB)")
    print(f"segments over hard cap ({HARD_CAP_SECONDS}s): {len(over_cap)}")
    for line in over_cap[:10]:
        print("   ", line)

    counts = Counter(per_sura.values())
    print(f"\nsegments per sura: min={min(per_sura.values())} "
          f"max={max(per_sura.values())} "
          f"median={sorted(per_sura.values())[len(per_sura) // 2]}")
    print("busiest suras:", sorted(per_sura.items(), key=lambda kv: -kv[1])[:5])
    return 0 if not over_cap else 1


if __name__ == "__main__":
    raise SystemExit(main())
