"""email password identity and email tokens

Revision ID: 0dd717701f7f
Revises: aae0de97dac4
Create Date: 2026-08-15 13:40:50.012878

TWO CHANGES, BOTH PURELY ADDITIVE. Nothing existing is altered or dropped, so
this is safe to run against a live database and safe to leave un-run for a
while: the code paths that need them are the new email endpoints, and every
Google and anonymous flow is untouched.

  auth_identity.password_hash   NULLABLE, and it stays null for every google
                                row. An email identity is an identity like any
                                other; the password is just what that provider
                                accepts as proof.

  email_token                   verification and password-reset tokens. Hashed,
                                expiring, single-use, ON DELETE CASCADE - the
                                same treatment auth_session and oauth_nonce get,
                                and for the same reason: a dumped table must not
                                hand anybody a working credential, and a reset
                                token IS a working credential.

THE DOWNGRADE DROPS PASSWORDS. Running it does not "undo" this migration in any
useful sense - it destroys the only copy of every learner's credential and
locks each of them out of their account permanently, since a hash cannot be
recovered from anywhere. It is written because Alembic revisions should be
reversible in shape; it is not something to run against a database anybody has
registered on.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits sqlmodel.sql.sqltypes.AutoString() for every str column,
# but Alembic's stock template does not import sqlmodel - so a generated
# revision raises NameError the first time it runs. Imported unconditionally
# here; an unused import in a revision file is harmless, a broken migration is
# not.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0dd717701f7f'
down_revision: Union[str, Sequence[str], None] = 'aae0de97dac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_token_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_token_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('auth_identity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_identity', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('email_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_token_purpose'))

    op.drop_table('email_token')
    # ### end Alembic commands ###
