"""auth foundation: auth_identity, device, auth_session; user account columns

Revision ID: 3edf85116114
Revises: eef4302d536f
Create Date: 2026-08-10 12:46:55.039464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits sqlmodel.sql.sqltypes.AutoString() for every str column,
# but Alembic's stock template does not import sqlmodel - so a generated
# revision raises NameError the first time it runs. Imported unconditionally
# here; an unused import in a revision file is harmless, a broken migration is
# not.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3edf85116114'
down_revision: Union[str, Sequence[str], None] = 'eef4302d536f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_identity_provider_subject'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_identity_user_provider')
    )
    with op.batch_alter_table('auth_identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_identity_user_id'), ['user_id'], unique=False)

    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_session_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_session_user_id'), ['user_id'], unique=False)

    op.create_table('device',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('display_name')
        batch_op.drop_column('email')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_user_id'))

    op.drop_table('device')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_session_token_hash'))

    op.drop_table('auth_session')
    with op.batch_alter_table('auth_identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_identity_user_id'))

    op.drop_table('auth_identity')
    # ### end Alembic commands ###
