"""Add picture to AuthIdentity

Revision ID: 60e5a56a50a5
Revises: c2b6c34132fa
Create Date: 2026-08-25 12:05:09.502085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits sqlmodel.sql.sqltypes.AutoString() for every str column,
# but Alembic's stock template does not import sqlmodel - so a generated
# revision raises NameError the first time it runs. Imported unconditionally
# here; an unused import in a revision file is harmless, a broken migration is
# not.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60e5a56a50a5'
down_revision: Union[str, Sequence[str], None] = 'c2b6c34132fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_identity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_identity', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
