"""oauth nonce for google login-csrf protection

Revision ID: aae0de97dac4
Revises: 3edf85116114
Create Date: 2026-08-10 17:31:18.971314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits sqlmodel.sql.sqltypes.AutoString() for every str column,
# but Alembic's stock template does not import sqlmodel - so a generated
# revision raises NameError the first time it runs. Imported unconditionally
# here; an unused import in a revision file is harmless, a broken migration is
# not.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aae0de97dac4'
down_revision: Union[str, Sequence[str], None] = '3edf85116114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_nonce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonce_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_nonce', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_nonce_nonce_hash'), ['nonce_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_nonce', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_nonce_nonce_hash'))

    op.drop_table('oauth_nonce')
    # ### end Alembic commands ###
