"""add lesson, quiz_question, lesson_progress tables

Revision ID: bb6b79a3a998
Revises: aae0de97dac4
Create Date: 2026-08-14 15:14:06.751127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate emits sqlmodel.sql.sqltypes.AutoString() for every str column,
# but Alembic's stock template does not import sqlmodel - so a generated
# revision raises NameError the first time it runs. Imported unconditionally
# here; an unused import in a revision file is harmless, a broken migration is
# not.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb6b79a3a998'
down_revision: Union[str, Sequence[str], None] = 'aae0de97dac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_uz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_uz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_codes', sa.JSON(), nullable=True),
    sa.Column('practice_sura', sa.Integer(), nullable=False),
    sa.Column('practice_aya', sa.Integer(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_order'), ['order'], unique=True)
        batch_op.create_index(batch_op.f('ix_lesson_slug'), ['slug'], unique=True)

    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('practice_done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_progress_user_lesson')
    )
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_uz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options_uz', sa.JSON(), nullable=True),
    sa.Column('options_ru', sa.JSON(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('explanation_uz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('explanation_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_question_lesson_id'), ['lesson_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_question_lesson_id'))

    op.drop_table('quiz_question')
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_lesson_id'))

    op.drop_table('lesson_progress')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_slug'))
        batch_op.drop_index(batch_op.f('ix_lesson_order'))

    op.drop_table('lesson')
    # ### end Alembic commands ###
