"""baseline: existing user and attempt schema

THIS REVISION IS NEVER RUN AGAINST THE EXISTING DATABASE. api/tilawah.db was
created by SQLModel's create_all() long before Alembic existed here, so it is
stamped with this revision rather than upgraded to it. The upgrade() body is
what a FRESH database gets, and it is verified byte-equivalent to the live
schema by tools/verify_baseline.py.

ONE KNOWN AND DELIBERATE DIVERGENCE. The live table carries server defaults on
the six columns that db/__init__.py:_add_missing_columns() bolted on after the
fact - `audio_consented BOOLEAN NOT NULL DEFAULT 0` and friends. Those defaults
exist only because ALTER TABLE ADD COLUMN on a NOT NULL column demands one;
they were never in the model. A fresh database built from this revision has no
server defaults there, which is correct - the application always supplies the
value - and matches what models.py actually declares.

Revision ID: eef4302d536f
Revises:
Create Date: 2026-08-10 12:26:41.824845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eef4302d536f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('audio_consented', sa.Boolean(), nullable=False),
    sa.Column('consent_seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sura', sa.Integer(), nullable=False),
    sa.Column('aya', sa.Integer(), nullable=False),
    sa.Column('start_word', sa.Integer(), nullable=False),
    sa.Column('num_words', sa.Integer(), nullable=False),
    sa.Column('include_bismillah', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clean', sa.Boolean(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('analysable', sa.Boolean(), nullable=False),
    sa.Column('snr_db', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('mean_prob', sa.Float(), nullable=False),
    sa.Column('expected_phonemes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('heard_phonemes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('silent_errors', sa.JSON(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wrong_flag', sa.Boolean(), nullable=False),
    sa.Column('wrong_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_created_at'))

    op.drop_table('attempt')
    op.drop_table('user')
    # ### end Alembic commands ###
